# Generated by Django 5.2.1 on 2025-06-03 05:34

import QuerySort.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(6, message='The event name must be at least 6 characters long.'), django.core.validators.RegexValidator("^[A-Za-zА-Яа-яЁё0-9 _\\-'&]+$")])),
                ('town', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(6, message='The town name must be at least 6 characters long.'), django.core.validators.RegexValidator("^[A-Za-zА-Яа-яЁё0-9 _\\-'&]+$")])),
                ('date', models.DateField(validators=[QuerySort.models.validate_event_date])),
                ('type', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(6, message='The event type must be at least 6 characters long.'), django.core.validators.RegexValidator("^[A-Za-zА-Яа-яЁё0-9 _\\-'&]+$")])),
                ('lectors', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(6, message='The event lectors must be at least 6 characters long.'), django.core.validators.RegexValidator("^[A-Za-zА-Яа-яЁё0-9 _\\-'&]+$")])),
            ],
        ),
    ]
