# Generated by Django 5.2.1 on 2025-06-03 09:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuerySort', '0002_alter_event_lectors_alter_event_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='lectors',
            field=models.CharField(default='Няма лектори.', max_length=255, validators=[django.core.validators.MinLengthValidator(6, message='The event lectors must be at least 6 characters long.')]),
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('Конференция', 'Конференция'), ('Уъркшоп', 'Уъркшоп'), ('Семинар', 'Семинар'), ('Други', 'Други')], max_length=255, validators=[django.core.validators.MinLengthValidator(6, message='The event type must be at least 6 characters long.'), django.core.validators.RegexValidator("^[A-Za-zА-Яа-яЁё0-9 _\\-'&]+$")]),
        ),
    ]
